# -*- coding: utf-8 -*-
"""Slicer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vH9slkZVRXGZnc99Rky0CClsvVlwGEm

**SINCRONIZZAZIONE CON GOOGLE DRIVE**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**INSTALLAZIONE DI SimpleITK**"""

pip install SimpleITK

import SimpleITK as sitk
import os

# Directory contenente le immagini PNG
input_dir = "/content/drive/MyDrive/results_gruppo_FB14"
output_file = "/content/drive/MyDrive/Challenge/output_volume.nrrd"

# Ottieni la lista dei file PNG ordinati
file_names = sorted([os.path.join(input_dir, f) for f in os.listdir(input_dir) if f.startswith('w6_d5')],key=lambda f: int(f.split('.')[0].split('_')[-1]))

# Crea una lista di immagini SimpleITK
images = [sitk.ReadImage(file_name) for file_name in file_names]

# Stack le immagini lungo la terza dimensione
volume = sitk.JoinSeries(images)

# Imposta la dimensione dello spazio voxel (opzionale)
volume.SetSpacing([images[0].GetSpacing()[0], images[0].GetSpacing()[1], 1.0])

# Salva il volume come file NRRD
sitk.WriteImage(volume, output_file)

print(f"Volume salvato in {output_file}")

# Directory contenente le immagini PNG
input_dir = "/content/drive/MyDrive/Challenge/DatasetOCT/masks/w6_d5"
output_file = "/content/drive/MyDrive/Challenge/manual_volume.nrrd"

# Ottieni la lista dei file PNG ordinati
file_names = sorted([os.path.join(input_dir, f) for f in os.listdir(input_dir) if f.startswith('w6_d5')],key=lambda f: int(f.split('.')[0].split('_')[-1]))

# Crea una lista di immagini SimpleITK
images = [sitk.ReadImage(file_name) for file_name in file_names]

# Stack le immagini lungo la terza dimensione
volume = sitk.JoinSeries(images)

# Imposta la dimensione dello spazio voxel (opzionale)
volume.SetSpacing([images[0].GetSpacing()[0], images[0].GetSpacing()[1], 1.0])

# Salva il volume come file NRRD
sitk.WriteImage(volume, output_file)

print(f"Volume salvato in {output_file}")