# -*- coding: utf-8 -*-
"""Estrazionedataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B7hGoLOUFjw-J1wsFfHv8KsPrW9R6v_b

**SINCRONIZZAZIONE CON GOOGLE DRIVE**
"""

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Extraction of the images and masks from the zip file

"""

from zipfile import ZipFile
import os
from tqdm import tqdm

zip_file_path='/content/drive/MyDrive/Challenge/DatasetOCT.zip'
working_folder='/content/drive/MyDrive/Challenge'

# Extract the zip file
with ZipFile(zip_file_path, 'r') as zip_ref:
    # Get the total number of files in the zip file
    total_files = len(zip_ref.infolist())

    # Create a progress bar using tqdm
    with tqdm(total=total_files, unit="file") as pbar:
        for member in zip_ref.infolist():
            # Extract each file individually and update the progress bar
            zip_ref.extract(member, working_folder)
            pbar.update(1)
